config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :users, through: :group_users
    has_many :group_users
    accepts_nested_attributes_for :group_users
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups, through: :group_users
  has_many :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to root_path(@group)
      flash[:notice] = "Group Created!"
    else
      render :new
      flash[:alert] = "Missed group-creation"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path(@group)
      flash[:notice] = "Group Updated!"
    else
      render :edit
      flash[:alert] = "Missed update"
    end
  end

private
  def set_group
    @group = Group.includes(:users).find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
       redirect_to :root, notice: "Edit Complete!"
    else
       flash[:alert] = "Miss Edit"
       render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 新規チャットグループ
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        = @group.errors.count
        件のエラーが発生しました。
        %ul
          - @group.errors.full_messages.each do |message|
            %li
              = message
  =form_for(@group) do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label :グループ名, '', class: "chat-group-form__label"
      .chat-group-form__field--right
        =f.text_field :name, placeholder: "グループ名を入力してください", class: "chat_group-form", id: "chat_group_name"
        .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバー, '', class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
          = b.label {b.check_box + b.text}
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit :save, class: "chat_group-form__action-btn"

app/views/groups/index.html.haml
.chat-side
  .chat-side__user
    .chat-side__user-content
      .chat-side__user-name
        = current_user.name
      = link_to  new_group_path(@group) do
        %i.fa.fa-pencil-square-o
      = link_to edit_user_path(current_user) do
        %i.fa.fa-cog
  %ul.chat-side__groups
    %li.chat-side__groups-list
      .chat-side__group
      - @groups.each do |group|
        .chat-side__group-name
          = group.name
        .chat-side__group-message
          = "まだメッセージはない"

.chat-main
  .chat-main__header
    .chat-main__header--group.clearfix
      .chat-main__header--group-edit-btn
        = link_to 'Edit'
      .chat-main__header--group-name
        werg
    .chat-main__header-members
      MEMBER:
      %i ewwwwwwf
  .chat-main__body
    .chat-main__body--messages-list
      .chat-main__message.clearfix
        .chat-main__message-name
          ewwwwwwf
        .chat-main__message-time
          2017/06/09 18:02:51
        .chat-main__message-body
          zxんm
          %img.chat-main__message-body-image
      .chat-main__message.clearfix
        .chat-main__message-name
          dsdsds
        .chat-main__message-time
          2017/06/09 18:33:51
        .chat-main__message-body
          dddddddddd
          %img.chat-main__message-body-image
  .chat-main__footer
    .new_message.chat-main__footer-form
      .chat-main__footer-body
        .message_body.message
        .submit
          Send

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        = @group.errors.count
        件のエラーが発生しました。
        %ul
          - @group.errors.full_messages.each do |message|
            %li
              = message
  =form_for(@group) do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label :グループ名, '', class: "chat-group-form__label"
      .chat-group-form__field--right
        =f.text_field :name, placeholder: "グループ名を入力してください", class: "chat_group-form", id: "chat_group_name"
        .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバー, '', class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
          = b.label {b.check_box + b.text}
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit :save, class: "chat_group-form__action-btn"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/flash"
    = yield

app/views/messages/index.html.haml
.chat-side
  .chat-side__user
    .chat-side__user-content
      .chat-side__user-name
        = current_user.name
        %i.fa.fa-pencil-square-o
      = link_to edit_user_path(current_user) do
        %i.fa.fa-cog
  .chat-side__groups
    .chat-side__groups-list
      .chat-side__group
        .chat-side__group-name
          = "group1"
        .chat-side__group-message
          = "まだメッセージはない"
        .chat-side__group-name
          = "group2"
        .chat-side__group-message
          = "まだメッセージはない"
.chat-main
  .chat-main__header
    .chat-main__header--group.clearfix
      .chat-main__header--group-edit-btn
        = link_to 'Edit'
      .chat-main__header--group-name
        werg
    .chat-main__header-members
      MEMBER:
      %i ewwwwwwf
  .chat-main__body
    .chat-main__body--messages-list
      .chat-main__message.clearfix
        .chat-main__message-name
          ewwwwwwf
        .chat-main__message-time
          2017/06/09 18:02:51
        .chat-main__message-body
          zxんm
          %img.chat-main__message-body-image
      .chat-main__message.clearfix
        .chat-main__message-name
          dsdsds
        .chat-main__message-time
          2017/06/09 18:33:51
        .chat-main__message-body
          dddddddddd
          %img.chat-main__message-body-image
  .chat-main__footer
    .new_message.chat-main__footer-form
      .chat-main__footer-body
        .message_body.message
        .submit
          Send

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'